version: "2.1"
services:
  code-server:
    image: ghcr.io/azat-ismagilov/cloud-overlayer-instance:main
    container_name: "live-${ID}"
    environment:
      - TZ=Etc/UTC
      - PASSWORD=${PASSWORD}
      - SUDO_PASSWORD=${PASSWORD}
      - CS_DISABLE_PROXY=1
    volumes:
      - ./config:/config
      - ./workspace:/workspace
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.live-${ID}-codeserver.rule=Host(`${ID}.live.ismagilov.de`)"
      - "traefik.http.routers.live-${ID}-codeserver.entrypoints=websecure"
      - "traefik.http.routers.live-${ID}-codeserver.tls.certresolver=letsencrypt"
      - "traefik.http.routers.live-${ID}-codeserver.service=svc_live-${ID}-codeserver"
      - "traefik.http.services.svc_live-${ID}-codeserver.loadbalancer.server.port=8443"

      - "traefik.http.routers.live-${ID}-overlay.rule=Host(`o${ID}.live.ismagilov.de`)"
      - "traefik.http.routers.live-${ID}-overlay.entrypoints=websecure"
      - "traefik.http.routers.live-${ID}-overlay.tls.certresolver=letsencrypt"
      - "traefik.http.routers.live-${ID}-overlay.service=svc_live-${ID}-overlay"
      - "traefik.http.services.svc_live-${ID}-overlay.loadbalancer.server.port=8080"

networks:
  web:
    external: true
